#!/bin/sh
set -e

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid

sed -i 's/#LoadModule proxy_wstunnel_module modules\/mod_proxy_wstunnel.so/LoadModule proxy_wstunnel_module modules\/mod_proxy_wstunnel.so/' /usr/local/apache2/conf/httpd.conf
sed -i 's/#LoadModule rewrite_module modules\/mod_rewrite.so/LoadModule rewrite_module modules\/mod_rewrite.so/' /usr/local/apache2/conf/httpd.conf

exec httpd -DFOREGROUND "$@"
