FROM docker.uncharted.software/alpine:3.16

LABEL org.opencontainers.image.title="TERArium Keycloak Theme"
LABEL org.opencontainers.image.description="Custom TERArium theme for Keycloak authentication"
LABEL org.opencontainers.image.licenses=Apache-2.0
LABEL org.opencontainers.image.documentation=https://github.com/DARPA-ASKEM/orchestration/blob/main/keycloak-theme/README.md
label org.opencontainers.image.source = "https://github.com/DARPA-ASKEM/orchestration"

WORKDIR /terarium

COPY terarium .
